name: Build latest
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - master
      - ConsoleDriver
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
#============================================
# ============== .NET 4.0 BUILD =============
# ===========================================
  build-mono4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile MCDzienny using mono
        shell: bash
        id: compile
        run: |
          msbuild MCDzienny.sln /p:Configuration=Release
          cp -R bin/Release_normal
          msbuild MCDzienny_/MCDzienny.csproj /p:Configuration=Release /t:Rebuild

      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release_normal'
          DEST_NAME: 'MCDzienny-forked'
